### ISSUE TITLE
Afval kalender changed

### ISSUE THREAD

**Issue by aceindy** [Martinvdm/garbage-nissewaard-homeassistant#2]
Hi @Martinvdm ....

Noticed the app started giving errors since today...
`Logger: homeassistant
Source: custom_components/nissewaard/sensor.py:265
First occurred: 9:58:40 AM (1273 occurrences)
Last logged: 8:34:41 PM`

Looks the URL changed from:
https://wasteapi.2go-mobile.com/api/{}
to: 
https://reinis.ximmio.com/modules/9dc25c8a-175a-4a41-b7a1-83f237a80b77/sitekalender/calendar.html?1000007525&somestreet---0%20%20%20---3207ZZ---Spijkenisse---Gemeente%20Spijkenisse

**Comment by Martinvdm** [comment]
You are right but I am still using this component with the old url ok. Working ok.

**Comment by aceindy** [comment]
@Martinvdm Hmm, that is weird....
It is a no go here
Are you from Spijkenisse as well??

**Comment by Martinvdm** [comment]
Yes, and working just fine. Only not today because of Christmas pickup .

**Comment by aceindy** [comment]
I've re-enabled the addon...and indeed..it still works, no more errors :D
